import { getAccessToken } from '../auth/authApi';
import type { Appointment, AppointmentHistory, AvailabilityBlock, AvailableProfessional, CatalogItem, InsurancePlan, InsuranceProvider, Professional, RescheduleRequest, Specialty, User } from '../types';

const API_URL = (import.meta.env.VITE_API_URL ?? 'http://localhost:8080').replace(/\/$/, '');
export class SchedulingApiError extends Error { constructor(public readonly status: number, message: string) { super(message); this.name = 'SchedulingApiError'; } }
function query(params: Record<string, string | undefined>): string { const entries = Object.entries(params).filter(([, value]) => value) as [string, string][]; return entries.length ? `?${new URLSearchParams(entries).toString()}` : ''; }
async function request<T>(path: string, init: RequestInit = {}): Promise<T> { const token = getAccessToken(); let response: Response; try { response = await fetch(`${API_URL}/api/v1${path}`, { ...init, credentials: 'include', headers: { Accept: 'application/json', ...(init.body ? { 'Content-Type': 'application/json' } : {}), ...(token ? { Authorization: `Bearer ${token}` } : {}), ...init.headers } }); } catch { throw new SchedulingApiError(0, 'No fue posible conectar con el servicio de citas.'); } if (!response.ok) { const problem = await response.json().catch(() => null) as { detail?: string; message?: string } | null; throw new SchedulingApiError(response.status, problem?.detail ?? problem?.message ?? 'No fue posible completar la solicitud.'); } return response.status === 204 ? undefined as T : response.json() as Promise<T>; }
type RawAvailability = { professionalId: number; professionalName: string; startAt: string; endAt: string };
type RawBlock = { id: number; locationId: number; locationName?: string; date: string; start: string; end: string };
type RawAppointment = Partial<Appointment> & { id: number | string; status: Appointment['status']; startAt: string; endAt?: string; specialty?: string; location?: string; professional?: string; patientFirstName?: string; patientLastName?: string };
const toBlock = (block: RawBlock): AvailabilityBlock => ({ id: String(block.id), locationId: String(block.locationId), locationName: block.locationName, startAt: `${block.date}T${block.start}`, endAt: `${block.date}T${block.end}` });
const toAppointment = (raw: RawAppointment, context?: Partial<Appointment>): Appointment => ({ id: String(raw.id), status: raw.status, professionalName: raw.professionalName ?? raw.professional ?? context?.professionalName ?? 'Profesional seleccionado', specialtyName: raw.specialtyName ?? raw.specialty ?? context?.specialtyName ?? 'Especialidad seleccionada', locationName: raw.locationName ?? raw.location ?? context?.locationName ?? 'Sede seleccionada', patientName: raw.patientName ?? ([raw.patientFirstName, raw.patientLastName].filter(Boolean).join(' ') || undefined), startAt: raw.startAt, endAt: raw.endAt, durationMinutes: raw.durationMinutes ?? context?.durationMinutes ?? 30, reason: raw.reason, rejectionReason: raw.rejectionReason, cancellationReason: raw.cancellationReason });

export const catalogsApi = { locations: () => request<CatalogItem[]>('/catalogs/locations'), insurancePlans: () => request<CatalogItem[]>('/catalogs/plans'), specialties: () => request<Specialty[]>('/specialties') };
export const appointmentsApi = {
  availability: async (filters: { locationId: string; specialtyId: string; professionalId?: string; date: string }): Promise<AvailableProfessional[]> => { const raw = await request<RawAvailability[]>(`/availability${query(filters)}`); const groups = new Map<string, AvailableProfessional>(); raw.forEach((item) => { const key = String(item.professionalId); const current = groups.get(key) ?? { id: key, name: item.professionalName, slots: [] }; current.slots.push({ startAt: item.startAt, endAt: item.endAt }); groups.set(key, current); }); return [...groups.values()]; },
  create: async (input: { professionalId: string; locationId: string; specialtyId: string; date: string; startTime: string; reason?: string }, context: Omit<Appointment, 'id' | 'status' | 'startAt'>) => toAppointment(await request<RawAppointment>('/appointments', { method: 'POST', body: JSON.stringify(input) }), context),
  mine: async (filters: { status?: string; from?: string; to?: string } = {}) => (await request<RawAppointment[]>(`/appointments${query(filters)}`)).map((item) => toAppointment(item)), detail: async (id: string) => toAppointment(await request<RawAppointment>(`/appointments/${id}`)), cancel: async (id: string, reason?: string) => toAppointment(await request<RawAppointment>(`/appointments/${id}/cancel`, { method: 'POST', body: JSON.stringify({ reason }) })), history: (id: string) => request<AppointmentHistory[]>(`/appointments/${id}/history`), reschedule: (id: string, input: { locationId?: string; date: string; startTime: string; reason?: string }) => request<RescheduleRequest>(`/appointments/${id}/reschedule-requests`, { method: 'POST', body: JSON.stringify(input) }),
  pendingSpecialized: async (): Promise<Appointment[]> => (await request<RawAppointment[]>('/admin/appointments/pending-specialized')).map((item) => toAppointment(item)), decide: async (id: string, decision: 'APPROVE' | 'REJECT', reason?: string) => toAppointment(await request<RawAppointment>(`/admin/appointments/${id}/decision`, { method: 'POST', body: JSON.stringify({ decision, reason }) })),
};
export const profileApi = { mine: () => request<User>('/users/me'), update: (phone: string) => request<User>('/users/me', { method: 'PATCH', body: JSON.stringify({ phone }) }) };
export const adminApi = { specialties: () => request<Specialty[]>('/admin/specialties'), professionals: () => request<Professional[]>('/admin/professionals'), eps: () => request<InsuranceProvider[]>('/admin/eps'), plans: () => request<InsurancePlan[]>('/admin/eps-plans'), createSpecialty: (input: { code: string; name: string; durationMinutes: 30 | 60; general: boolean }) => request<Specialty>('/admin/specialties', { method: 'POST', body: JSON.stringify(input) }), updateSpecialty: (id: string, input: Partial<{ name: string; durationMinutes: 30 | 60; active: boolean }>) => request<Specialty>(`/admin/specialties/${id}`, { method: 'PATCH', body: JSON.stringify(input) }), createEps: (input: { code: string; name: string }) => request<InsuranceProvider>('/admin/eps', { method: 'POST', body: JSON.stringify(input) }), updateEps: (id: string, input: Partial<{ code: string; name: string; active: boolean }>) => request<InsuranceProvider>(`/admin/eps/${id}`, { method: 'PATCH', body: JSON.stringify(input) }), createPlan: (input: { epsId: string; code: string; name: string }) => request<InsurancePlan>('/admin/eps-plans', { method: 'POST', body: JSON.stringify(input) }), updatePlan: (id: string, input: Partial<{ code: string; name: string; active: boolean }>) => request<InsurancePlan>(`/admin/eps-plans/${id}`, { method: 'PATCH', body: JSON.stringify(input) }), createProfessional: (input: Record<string, unknown>) => request<{ id: string }>('/admin/professionals', { method: 'POST', body: JSON.stringify(input) }), assignSpecialties: (id: string, specialtyIds: string[], primarySpecialtyId: string) => request<void>(`/admin/professionals/${id}/specialties`, { method: 'PUT', body: JSON.stringify({ specialtyIds, primarySpecialtyId }) }), assignLocations: (id: string, locationIds: string[]) => request<void>(`/admin/professionals/${id}/locations`, { method: 'PUT', body: JSON.stringify({ locationIds }) }), setActive: (id: string, active: boolean) => request<void>(`/admin/professionals/${id}/active`, { method: 'PATCH', body: JSON.stringify({ active }) }), inbox: async (filters: { type?: string; locationId?: string; professionalId?: string; specialtyId?: string; date?: string } = {}) => (await request<RawAppointment[]>(`/admin/inbox${query(filters)}`)).map((item) => toAppointment(item)), decide: (id: string, decision: 'APPROVE' | 'REJECT', reason?: string) => appointmentsApi.decide(id, decision, reason), decideReschedule: (id: string, decision: 'APPROVE' | 'REJECT', reason?: string) => request<RescheduleRequest>(`/admin/reschedule-requests/${id}/decision`, { method: 'POST', body: JSON.stringify({ decision, reason }) }) };
export const professionalApi = { appointments: async (filters: { from: string; to: string; locationId?: string }) => (await request<RawAppointment[]>(`/professional/appointments${query(filters)}`)).map((item) => toAppointment(item)), close: async (id: string, status: 'COMPLETED' | 'NO_SHOW') => toAppointment(await request<RawAppointment>(`/professional/appointments/${id}/closure`, { method: 'POST', body: JSON.stringify({ status }) })) };
export const availabilityApi = { listMine: async (date?: string, locationId?: string) => (await request<RawBlock[]>(`/professional/availability-blocks${query({ date, locationId })}`)).map(toBlock), create: async (input: Omit<AvailabilityBlock, 'id' | 'locationName'>) => { const [date, startTime] = input.startAt.split('T'); const [, endTime] = input.endAt.split('T'); return toBlock(await request<RawBlock>('/professional/availability-blocks', { method: 'POST', body: JSON.stringify({ locationId: input.locationId, date, startTime, endTime }) })); }, update: async (id: string, input: Partial<Omit<AvailabilityBlock, 'id' | 'locationName'>>) => { const [date, startTime] = input.startAt?.split('T') ?? []; const [, endTime] = input.endAt?.split('T') ?? []; return toBlock(await request<RawBlock>(`/professional/availability-blocks/${id}`, { method: 'PATCH', body: JSON.stringify({ locationId: input.locationId, date, startTime, endTime }) })); }, remove: (id: string) => request<void>(`/professional/availability-blocks/${id}`, { method: 'DELETE' }) };
export function schedulingErrorMessage(error: unknown): string { if (!(error instanceof SchedulingApiError)) return 'Ocurrió un error inesperado.'; if (error.status === 401) return 'Tu sesión venció. Inicia sesión nuevamente.'; if (error.status === 403) return 'No tienes permiso para realizar esta acción.'; if (error.status === 404) return 'El recurso solicitado no está disponible.'; if (error.status === 409) return 'La operación entra en conflicto con el estado actual de la cita.'; if (error.status === 400) return 'Revisa los datos ingresados.'; return error.message; }
