import { getAccessToken } from '../auth/authApi';
import type { Appointment, AvailabilityBlock, AvailableProfessional, CatalogItem, Professional, Specialty } from '../types';

const API_URL = (import.meta.env.VITE_API_URL ?? 'http://localhost:8080').replace(/\/$/, '');
export class SchedulingApiError extends Error { constructor(public readonly status: number, message: string) { super(message); this.name = 'SchedulingApiError'; } }
function query(params: Record<string, string | undefined>): string { const entries = Object.entries(params).filter(([, value]) => value) as [string, string][]; return entries.length ? `?${new URLSearchParams(entries).toString()}` : ''; }
async function request<T>(path: string, init: RequestInit = {}): Promise<T> { const token = getAccessToken(); let response: Response; try { response = await fetch(`${API_URL}/api/v1${path}`, { ...init, credentials: 'include', headers: { Accept: 'application/json', ...(init.body ? { 'Content-Type': 'application/json' } : {}), ...(token ? { Authorization: `Bearer ${token}` } : {}), ...init.headers } }); } catch { throw new SchedulingApiError(0, 'No fue posible conectar con el servicio de citas.'); } if (!response.ok) { const problem = await response.json().catch(() => null) as { detail?: string } | null; throw new SchedulingApiError(response.status, problem?.detail ?? 'No fue posible completar la solicitud.'); } return response.status === 204 ? undefined as T : response.json() as Promise<T>; }
type RawAvailability = { professionalId: number; professionalName: string; startAt: string; endAt: string };
type RawBlock = { id: number; locationId: number; date: string; start: string; end: string };
type RawPending = { id: number; startAt: string; endAt: string; specialty: string; location: string; patientFirstName: string; patientLastName: string };
const toBlock = (block: RawBlock): AvailabilityBlock => ({ id: String(block.id), locationId: String(block.locationId), startAt: `${block.date}T${block.start}`, endAt: `${block.date}T${block.end}` });
const toAppointment = (raw: Partial<Appointment> & { id: number | string; status: Appointment['status']; startAt: string; endAt?: string }, context?: Partial<Appointment>): Appointment => ({ id: String(raw.id), status: raw.status, professionalName: raw.professionalName ?? context?.professionalName ?? 'Profesional seleccionado', specialtyName: raw.specialtyName ?? context?.specialtyName ?? 'Especialidad seleccionada', locationName: raw.locationName ?? context?.locationName ?? 'Sede seleccionada', startAt: raw.startAt, durationMinutes: raw.durationMinutes ?? context?.durationMinutes ?? 30, rejectionReason: raw.rejectionReason });

export const catalogsApi = { locations: () => request<CatalogItem[]>('/catalogs/locations'), insurancePlans: () => request<CatalogItem[]>('/catalogs/plans'), specialties: () => request<Specialty[]>('/specialties') };
export const appointmentsApi = {
  availability: async (filters: { locationId: string; specialtyId: string; professionalId?: string; date: string }): Promise<AvailableProfessional[]> => { const raw = await request<RawAvailability[]>(`/availability${query(filters)}`); const groups = new Map<string, AvailableProfessional>(); raw.forEach((item) => { const key = String(item.professionalId); const current = groups.get(key) ?? { id: key, name: item.professionalName, slots: [] }; current.slots.push({ startAt: item.startAt, endAt: item.endAt }); groups.set(key, current); }); return [...groups.values()]; },
  create: async (input: { professionalId: string; locationId: string; specialtyId: string; date: string; startTime: string; reason?: string }, context: Omit<Appointment, 'id' | 'status' | 'startAt'>) => toAppointment(await request<Partial<Appointment> & { id: number; status: Appointment['status']; startAt: string; endAt: string }>('/appointments', { method: 'POST', body: JSON.stringify(input) }), context),
  pendingSpecialized: async (): Promise<Appointment[]> => (await request<RawPending[]>('/admin/appointments/pending-specialized')).map((item) => ({ id: String(item.id), status: 'REQUESTED', professionalName: `${item.patientFirstName} ${item.patientLastName}`, specialtyName: item.specialty, locationName: item.location, startAt: item.startAt, durationMinutes: 30 })),
  decide: async (id: string, decision: 'APPROVE' | 'REJECT', reason?: string) => toAppointment(await request<Partial<Appointment> & { id: number; status: Appointment['status']; startAt: string; endAt: string }>(`/admin/appointments/${id}/decision`, { method: 'POST', body: JSON.stringify({ decision, reason }) })),
};
export const adminApi = { specialties: () => request<Specialty[]>('/admin/specialties'), professionals: () => request<Professional[]>('/admin/professionals'), createSpecialty: (input: { code: string; name: string; durationMinutes: 30 | 60; general: boolean }) => request<Specialty>('/admin/specialties', { method: 'POST', body: JSON.stringify(input) }), updateSpecialty: (id: string, input: Partial<{ name: string; durationMinutes: 30 | 60; active: boolean }>) => request<Specialty>(`/admin/specialties/${id}`, { method: 'PATCH', body: JSON.stringify(input) }), createProfessional: (input: Record<string, unknown>) => request<{ id: string }>('/admin/professionals', { method: 'POST', body: JSON.stringify(input) }), assignSpecialties: (id: string, specialtyIds: string[], primarySpecialtyId: string) => request<void>(`/admin/professionals/${id}/specialties`, { method: 'PUT', body: JSON.stringify({ specialtyIds, primarySpecialtyId }) }), assignLocations: (id: string, locationIds: string[]) => request<void>(`/admin/professionals/${id}/locations`, { method: 'PUT', body: JSON.stringify({ locationIds }) }), setActive: (id: string, active: boolean) => request<void>(`/admin/professionals/${id}/active`, { method: 'PATCH', body: JSON.stringify({ active }) }) };
export const availabilityApi = { listMine: async (date?: string, locationId?: string) => (await request<RawBlock[]>(`/professional/availability-blocks${query({ date, locationId })}`)).map(toBlock), create: async (input: Omit<AvailabilityBlock, 'id' | 'locationName'>) => { const [date, startTime] = input.startAt.split('T'); const [, endTime] = input.endAt.split('T'); return toBlock(await request<RawBlock>('/professional/availability-blocks', { method: 'POST', body: JSON.stringify({ locationId: input.locationId, date, startTime, endTime }) })); }, update: async (id: string, input: Partial<Omit<AvailabilityBlock, 'id' | 'locationName'>>) => { const [date, startTime] = input.startAt?.split('T') ?? []; const [, endTime] = input.endAt?.split('T') ?? []; return toBlock(await request<RawBlock>(`/professional/availability-blocks/${id}`, { method: 'PATCH', body: JSON.stringify({ locationId: input.locationId, date, startTime, endTime }) })); }, remove: (id: string) => request<void>(`/professional/availability-blocks/${id}`, { method: 'DELETE' }) };
export function schedulingErrorMessage(error: unknown): string { if (!(error instanceof SchedulingApiError)) return 'Ocurrió un error inesperado.'; if (error.status === 401) return 'Tu sesión venció. Inicia sesión nuevamente.'; if (error.status === 403) return 'No tienes permiso para realizar esta acción.'; if (error.status === 404) return 'El recurso solicitado no está disponible.'; if (error.status === 409) return 'El horario dejó de estar disponible. Selecciona otro horario.'; if (error.status === 400) return 'Revisa los datos ingresados.'; return error.message; }
