import React, { useEffect, useState } from 'react';
import { Calendar, CheckCircle2, ChevronRight, Clock, MapPin, Shield, X } from 'lucide-react';
import { appointmentsApi, catalogsApi, SchedulingApiError, schedulingErrorMessage } from '../api/schedulingApi';
import { bogotaToday, localTime } from '../api/bogotaTime';
import type { Appointment, AvailableProfessional, CatalogItem, Specialty } from '../types';

interface Props { isOpen: boolean; onClose: () => void; onAppointmentBooked: (appointment: Appointment) => void; }
const SLOT_TAKEN_MESSAGE = 'La franja seleccionada dejó de estar disponible. Elige otro horario.';
const STATUS_LABEL: Record<string, string> = { APPROVED: 'Cita aprobada', REQUESTED: 'Solicitud enviada a revisión administrativa' };

export function BookAppointmentModal({ isOpen, onClose, onAppointmentBooked }: Props) {
  const [step, setStep] = useState<1 | 2 | 3 | 4>(1);
  const [locations, setLocations] = useState<CatalogItem[]>([]); const [specialties, setSpecialties] = useState<Specialty[]>([]);
  const [locationId, setLocationId] = useState(''); const [specialtyId, setSpecialtyId] = useState('');
  const [date, setDate] = useState(''); const [booked, setBooked] = useState<Appointment | null>(null); const [professionals, setProfessionals] = useState<AvailableProfessional[]>([]);
  const [professionalId, setProfessionalId] = useState(''); const [startAt, setStartAt] = useState(''); const [reason, setReason] = useState('');
  const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const selectedProfessional = professionals.find((professional) => professional.id === professionalId);
  const selectedSpecialty = specialties.find((specialty) => specialty.id === specialtyId);

  useEffect(() => { if (!isOpen) return; setLoading(true); setError(''); Promise.all([catalogsApi.locations(), catalogsApi.specialties()]).then(([nextLocations, nextSpecialties]) => { setLocations(nextLocations); setSpecialties(nextSpecialties); }).catch((cause) => setError(schedulingErrorMessage(cause))).finally(() => setLoading(false)); }, [isOpen]);
  const loadAvailability = () => { if (!locationId || !specialtyId || !date) { setProfessionals([]); return Promise.resolve(); } setLoading(true); return appointmentsApi.availability({ locationId, specialtyId, date }).then(setProfessionals).catch((cause) => setError(schedulingErrorMessage(cause))).finally(() => setLoading(false)); };
  // Abrir el modal o cambiar un filtro invalida profesional y franja, y reconsulta la disponibilidad.
  useEffect(() => { if (!isOpen) return; setProfessionalId(''); setStartAt(''); setError(''); void loadAvailability(); }, [isOpen, locationId, specialtyId, date]);
  if (!isOpen) return null;
  const today = bogotaToday();
  const canContinue = step === 1 ? Boolean(locationId && specialtyId && date && date >= today) : step === 2 ? Boolean(selectedProfessional) : step === 3 ? Boolean(startAt) : true;
  const close = () => { setStep(1); setBooked(null); setReason(''); setError(''); onClose(); };
  const finish = async () => { if (!professionalId || !locationId || !specialtyId || !startAt || !selectedProfessional || !selectedSpecialty) return; setLoading(true); setError(''); try { const appointment = await appointmentsApi.create({ professionalId, locationId, specialtyId, date, startTime: localTime(startAt), reason: reason.trim() || undefined }, { professionalName: selectedProfessional.name, specialtyName: selectedSpecialty.name, locationName: locations.find((item) => item.id === locationId)?.name ?? 'Sede seleccionada', durationMinutes: selectedSpecialty.durationMinutes }); setBooked(appointment); onAppointmentBooked(appointment); } catch (cause) { if (cause instanceof SchedulingApiError && cause.status === 409) { setStartAt(''); setStep(3); await loadAvailability(); setError(SLOT_TAKEN_MESSAGE); } else setError(schedulingErrorMessage(cause)); } finally { setLoading(false); } };

  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Agendar cita">
    <div className="w-full max-w-2xl bg-white rounded-2xl shadow-2xl border border-slate-100 overflow-hidden flex flex-col max-h-[90vh]">
      <header className="px-6 py-4 border-b border-slate-100 flex justify-between bg-slate-50/50"><div><span className="text-[11px] font-semibold tracking-wider text-blue-600 uppercase">Agendar nueva cita</span><h3 className="text-lg font-bold text-slate-900">{booked ? 'Resultado' : `Paso ${step} de 4`}</h3></div><button type="button" onClick={close} className="p-2 text-slate-400 hover:text-slate-700" aria-label="Cerrar"><X /></button></header>
      <div className="h-1.5 bg-slate-100"><div className="h-full bg-blue-600" style={{ width: `${booked ? 100 : step * 25}%` }} /></div>
      <main className="p-6 overflow-y-auto space-y-4 flex-1">
        {error && <p role="alert" className="p-3 text-xs text-red-700 bg-red-50 border border-red-200 rounded-xl">{error}</p>}
        {loading && <p className="text-sm text-slate-500">Consultando información disponible…</p>}
        {booked && <div className="space-y-3 text-center"><CheckCircle2 className={`mx-auto w-10 h-10 ${booked.status === 'APPROVED' ? 'text-emerald-600' : 'text-blue-600'}`} /><p className="text-base font-bold text-slate-900">{STATUS_LABEL[booked.status] ?? booked.status}</p><p className="text-xs text-slate-500">Estado: <strong>{booked.status}</strong> · {booked.specialtyName} · {date} {localTime(booked.startAt)}</p></div>}
        {!booked && step === 1 && <><p className="text-sm text-slate-600">Selecciona la sede, la especialidad y la fecha de tu atención.</p><div className="grid sm:grid-cols-3 gap-4"><label className="text-xs font-semibold text-slate-700">Sede<select value={locationId} onChange={(event) => setLocationId(event.target.value)} className="mt-2 w-full p-3 border border-slate-200 rounded-xl bg-white"><option value="">Selecciona una sede</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-xs font-semibold text-slate-700">Especialidad<select value={specialtyId} onChange={(event) => setSpecialtyId(event.target.value)} className="mt-2 w-full p-3 border border-slate-200 rounded-xl bg-white"><option value="">Selecciona una especialidad</option>{specialties.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.durationMinutes} min</option>)}</select></label><label className="text-xs font-semibold text-slate-700">Fecha<input type="date" min={today} value={date} onChange={(event) => setDate(event.target.value)} className="mt-2 w-full p-3 border border-slate-200 rounded-xl" /></label></div></>}
        {!booked && step === 2 && <><p className="text-sm text-slate-600">Elige un profesional disponible para la fecha seleccionada.</p>{professionals.length ? <div className="space-y-3">{professionals.map((professional) => <button type="button" key={professional.id} onClick={() => { setProfessionalId(professional.id); setStartAt(''); }} className={`w-full p-4 text-left rounded-xl border ${professionalId === professional.id ? 'border-blue-600 bg-blue-50 ring-2 ring-blue-500/20' : 'border-slate-200 hover:bg-slate-50'}`}><strong className="text-sm text-slate-900">{professional.name}</strong><span className="block text-xs text-slate-500 mt-1">{professional.slots.length} horarios disponibles</span></button>)}</div> : !loading && <p className="p-5 text-center text-sm text-slate-500 bg-slate-50 rounded-xl">No hay profesionales disponibles con estos filtros.</p>}</>}
        {!booked && step === 3 && <><p className="text-sm text-slate-600">Horarios de {selectedProfessional?.name} el {date}.</p>{selectedProfessional && <div className="mt-4 grid grid-cols-2 sm:grid-cols-4 gap-2">{selectedProfessional.slots.map((slot) => <button type="button" key={slot.startAt} onClick={() => setStartAt(slot.startAt)} className={`py-2 px-3 rounded-lg border text-xs ${startAt === slot.startAt ? 'border-blue-600 bg-blue-50 text-blue-700' : 'border-slate-200 text-slate-700'}`}><Clock className="inline w-3 h-3 mr-1" />{localTime(slot.startAt)}</button>)}</div>}</>}
        {!booked && step === 4 && <><div className="p-4 rounded-xl bg-gradient-to-br from-[#07152B] to-[#0E2952] text-white"><p className="text-xs text-blue-200">Resumen de solicitud</p><p className="font-semibold mt-1">{selectedProfessional?.name}</p><p className="text-xs text-slate-300">{selectedSpecialty?.name} · {selectedSpecialty?.durationMinutes} min</p><p className="text-xs text-slate-300 mt-2"><MapPin className="inline w-3 h-3 mr-1" />{locations.find((item) => item.id === locationId)?.name}</p><p className="text-xs text-slate-300 mt-1"><Calendar className="inline w-3 h-3 mr-1" />{date} · {startAt && localTime(startAt)}</p></div><label className="block text-xs font-semibold text-slate-700">Motivo de consulta<textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3} className="mt-2 w-full p-3 border border-slate-200 rounded-xl text-sm" placeholder="Describe brevemente el motivo (opcional)" /></label><p className="p-3 bg-blue-50 border border-blue-100 rounded-xl text-xs text-blue-800"><Shield className="inline w-4 h-4 mr-2 text-blue-600" />Las citas generales se aprueban de inmediato. Las especializadas quedan pendientes de decisión administrativa.</p></>}
      </main>
      <footer className="px-6 py-4 border-t border-slate-100 flex justify-between bg-slate-50/50">{booked ? <button type="button" onClick={close} className="ml-auto px-5 py-2.5 bg-blue-600 text-white text-xs font-semibold rounded-xl">Cerrar</button> : <><button type="button" disabled={step === 1 || loading} onClick={() => setStep((current) => (current - 1) as 1 | 2 | 3 | 4)} className="px-4 py-2 text-xs font-semibold text-slate-600 disabled:opacity-40">← Anterior</button>{step < 4 ? <button type="button" disabled={!canContinue || loading} onClick={() => setStep((current) => (current + 1) as 1 | 2 | 3 | 4)} className="px-5 py-2.5 bg-blue-600 text-white text-xs font-semibold rounded-xl disabled:opacity-50">Continuar <ChevronRight className="inline w-3.5 h-3.5" /></button> : <button type="button" disabled={loading} onClick={finish} className="px-5 py-2.5 bg-emerald-600 text-white text-xs font-semibold rounded-xl disabled:opacity-50"><CheckCircle2 className="inline w-4 h-4 mr-1" />Confirmar</button>}</>}</footer>
    </div>
  </div>;
}
