import { useState } from 'react';
import { ArrowLeft, CheckCircle2, KeyRound, Mail } from 'lucide-react';
import { authErrorMessage, requestPasswordRecovery, resetPassword } from '../auth/authApi';

const Shell = ({ children }: { children: React.ReactNode }) => <main className="w-full max-w-md bg-white rounded-3xl shadow-xl shadow-slate-200/70 border border-slate-100 p-8 space-y-6"><div className="w-11 h-11 grid place-items-center rounded-xl bg-gradient-to-tr from-blue-600 to-sky-400 text-white"><KeyRound className="w-5 h-5" /></div>{children}</main>;

export function PasswordRecoveryScreen({ onBack, onReset }: { onBack: () => void; onReset: () => void }) {
  const [email, setEmail] = useState(''); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { await requestPasswordRecovery(email); setMessage('Si existe una cuenta asociada, recibirás instrucciones para restablecer la contraseña.'); } catch (cause) { setError(authErrorMessage(cause)); } finally { setLoading(false); } };
  return <Shell><button type="button" onClick={onBack} className="text-xs text-slate-500 hover:text-blue-600"><ArrowLeft className="inline w-3 h-3 mr-1" />Volver al acceso</button><div><h1 className="text-2xl font-bold">Recuperar contraseña</h1><p className="mt-1 text-sm text-slate-500">Ingresa tu correo para solicitar el restablecimiento.</p></div>{message ? <div className="space-y-3"><p role="status" className="p-3 text-sm text-emerald-800 bg-emerald-50 rounded-xl"><CheckCircle2 className="inline w-4 h-4 mr-1" />{message}</p><button type="button" onClick={onReset} className="w-full py-3 bg-blue-600 text-white text-sm font-semibold rounded-xl">Tengo un token temporal</button></div> : <form onSubmit={submit} className="space-y-4">{error && <p role="alert" className="p-3 text-xs text-red-700 bg-red-50 rounded-xl">{error}</p>}<label className="block text-xs font-semibold text-slate-700">Correo electrónico<div className="relative mt-2"><Mail className="absolute left-3 top-3.5 w-4 h-4 text-slate-400" /><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="w-full pl-10 p-3 border border-slate-200 rounded-xl" placeholder="usuario@ejemplo.com" /></div></label><button disabled={loading} className="w-full py-3 bg-blue-600 text-white text-sm font-semibold rounded-xl disabled:opacity-60">{loading ? 'Enviando…' : 'Solicitar restablecimiento'}</button></form>}</Shell>;
}

export function PasswordResetScreen({ onBack }: { onBack: () => void }) {
  const [token, setToken] = useState(''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (password !== confirmation) { setError('Las contraseñas deben coincidir.'); return; } setLoading(true); setError(''); try { await resetPassword(token, password); setMessage('Contraseña actualizada. Ya puedes iniciar sesión.'); } catch (cause) { setError(authErrorMessage(cause)); } finally { setLoading(false); } };
  return <Shell><button type="button" onClick={onBack} className="text-xs text-slate-500 hover:text-blue-600"><ArrowLeft className="inline w-3 h-3 mr-1" />Volver al acceso</button><div><h1 className="text-2xl font-bold">Nueva contraseña</h1><p className="mt-1 text-sm text-slate-500">Usa el token temporal recibido para crear una contraseña segura.</p></div>{message ? <p role="status" className="p-3 text-sm text-emerald-800 bg-emerald-50 rounded-xl">{message}</p> : <form onSubmit={submit} className="space-y-3">{error && <p role="alert" className="p-3 text-xs text-red-700 bg-red-50 rounded-xl">{error}</p>}<input required value={token} onChange={(event) => setToken(event.target.value)} className="w-full p-3 border border-slate-200 rounded-xl text-sm" placeholder="Token temporal" /><input required minLength={8} type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="w-full p-3 border border-slate-200 rounded-xl text-sm" placeholder="Nueva contraseña" /><input required minLength={8} type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="w-full p-3 border border-slate-200 rounded-xl text-sm" placeholder="Confirmar contraseña" /><button disabled={loading} className="w-full py-3 bg-blue-600 text-white text-sm font-semibold rounded-xl disabled:opacity-60">{loading ? 'Actualizando…' : 'Actualizar contraseña'}</button></form>}</Shell>;
}
